"""
FastAPI Backend — Summit Coffee Co. Supply Chain Analytics Agent
================================================================
Endpoints
  GET  /                  health ping
  GET  /health            data-source row counts
  GET  /tools             registered analytics tools
  GET  /roles             RBAC role definitions
  GET  /sample-questions  20 pre-built questions
  POST /ask               main analytics endpoint
"""

# ── stdlib ────────────────────────────────────────────────────────────────────
import os
import sys
import logging
from typing import Any, Dict, List, Optional

# ── third-party ───────────────────────────────────────────────────────────────
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from dotenv import load_dotenv

# ── env + path ────────────────────────────────────────────────────────────────
load_dotenv()
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# ── local ─────────────────────────────────────────────────────────────────────
from agent import plan_and_execute
from tool_registry import get_tool_descriptions
from data_loader import get_all_data
from rbac import get_roles_info

# ── logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# ── app ───────────────────────────────────────────────────────────────────────
app = FastAPI(
    title="Summit Coffee Co. Supply Chain Analytics Agent",
    description="AI-powered supply chain analytics agent powered by Claude 3.5 Sonnet",
    version="2.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Pydantic models ───────────────────────────────────────────────────────────

class SessionEntry(BaseModel):
    """A single rated Q&A pair carried forward from the session cache."""
    question: str
    summary:  str
    rating:   str            # 'excellent' | 'moderate' | 'average' | 'worst'
    ts:       Optional[str] = None


class QuestionRequest(BaseModel):
    question:        str
    role:            str               = "executive"   # 'executive' | 'analyst' | 'viewer'
    session_context: List[SessionEntry] = []           # rated history from this session


class AnalyticsResponse(BaseModel):
    tool_name:  Optional[str]
    table:      List[Dict[str, Any]]
    summary:    str
    narrative:  str
    trace:      List[str]
    tokens_used: int
    latency_ms:  int
    extra_data:  Optional[Dict[str, Any]] = None
    error:       Optional[str]            = None


# ── Routes ────────────────────────────────────────────────────────────────────

@app.get("/")
def root():
    """Health ping."""
    return {"status": "ok", "service": "Summit Coffee Co. Analytics Agent"}


@app.get("/health")
def health():
    """Return row counts for every loaded data source."""
    try:
        data = get_all_data()
        return {
            "status": "healthy",
            "data_sources": {k: len(v) for k, v in data.items()},
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/tools")
def list_tools():
    """List all registered analytics tools."""
    return {"tools": get_tool_descriptions()}


@app.get("/roles")
def list_roles():
    """Return all available roles and their data-access permissions."""
    return {"roles": get_roles_info()}


@app.post("/ask", response_model=AnalyticsResponse)
def ask(request: QuestionRequest):
    """
    Main analytics endpoint.
    Accepts a natural-language question and returns a structured analysis
    (table + narrative + trace) generated by the Claude agent.
    """
    if not request.question.strip():
        raise HTTPException(status_code=400, detail="Question cannot be empty")

    role = request.role.lower() if request.role else "executive"
    logger.info("Question: %s | Role: %s", request.question, role)

    session_ctx = [e.dict() for e in request.session_context] if request.session_context else []
    result = plan_and_execute(request.question, role=role, session_context=session_ctx)
    return AnalyticsResponse(**result)


# ── Sample questions ──────────────────────────────────────────────────────────

_SAMPLE_QUESTIONS = [
    # SKU Profitability
    ("Q1",  "What are our top 10 and bottom 10 SKUs by actual realized gross margin percentage?"),
    ("Q2",  "For Ethiopian Yirgacheffe 12oz, show me the theoretical margin at every pricing tier, then compare it to the actual blended margin we've realized in transactions."),
    ("Q3",  "Which SKUs have the highest gap between their MSRP and the average price we actually sell them at?"),
    ("Q4",  "Identify any transactions where a customer was charged a price that doesn't match their assigned pricing tier."),
    # Customer
    ("Q5",  "Who are our top 5 customers by total revenue, and what is their fully-loaded margin after COGS and shipping?"),
    ("Q6",  "Give me a full profitability breakdown for Coastal Cafe Group - revenue, COGS, shipping cost, and net margin broken down by SKU."),
    ("Q7",  "What is our customer concentration risk? Show cumulative revenue percentage by customer."),
    ("Q8",  "Compare the profitability of our wholesale channel vs. Shopify DTC vs. Amazon. Which channel should we invest in?"),
    # Shipping
    ("Q9",  "What percentage of our total shipping spend goes to expedited and overnight shipping, broken down by month?"),
    ("Q10", "Which customers have the highest shipping cost as a percentage of their order value?"),
    ("Q11", "If we converted all expedited shipments to standard shipping rates, what would our annual savings be?"),
    ("Q12", "Compare UPS, FedEx, and USPS on cost per pound by service type. Which carrier should we consolidate to?"),
    # Budget
    ("Q13", "Show me plan vs. actual for every cost category for the last 6 months."),
    ("Q14", "What is the root cause of our shipping budget overrun?"),
    ("Q15", "Are we on track to hit our revenue budget for the full 6-month period?"),
    # Strategic
    ("Q16", "What would happen to our overall profitability if the cost of Brazilian coffee increased by 50% due to tariffs?"),
    ("Q17", "Which account manager's portfolio has the best and worst blended margin?"),
    ("Q18", "Build me a monthly P&L that shows Revenue, COGS, Gross Margin, Shipping Cost, Net Margin for each of the 6 months."),
    ("Q19", "We're considering dropping all T0 customers and moving that volume to T1 pricing. Model the revenue and margin impact assuming we retain 60% of the volume."),
    ("Q20", "Give me an executive dashboard summary: What are the 3 most important things leadership should know about our business performance?"),
]


@app.get("/sample-questions")
def sample_questions():
    """Return all 20 pre-built sample questions."""
    return {
        "questions": [{"id": qid, "text": text} for qid, text in _SAMPLE_QUESTIONS]
    }
